menu:
  about: /about
  download: /download
  documentation: /documentation
  tutorials: /tutorials
  gallery: /gallery
  community: /community
  development: /development



# Static files
vendors: vendors
css: css
js: js
images: images

# Theme version
version: 0.4.5.1
